### ISSUE TITLE
Update release after adding new MCU

### ISSUE THREAD

**Issue by no111u3** [Rahix/avr-device#49]
Could you tell me, do you have plan to create new release after add new MCU support?

**Comment by Rahix** [comment]
I don't really have a release schedule, but yeah, I aim to have support for new MCUs not wait too long in the repo before issuing a new release.

**Comment by no111u3** [comment]
Thanks for answer, I ask because I have some plans to update avr-hal too for support my mcu - atmega48p.

**Comment by Rahix** [comment]
You can already start working on that with by patching the `avr-device` dependency in `avr-hal` to point to a locally built version.  Add this to the top-level `Cargo.toml` in `avr-hal`:

```toml
[patch.crates-io]
avr-device = { path = "/path/to/whereever/you/built/avr-device" }
```
